# Generated by Django 6.0.3 on 2026-04-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=255)),
                ('rate_type', models.CharField(max_length=100)),
                ('rate_value', models.FloatField()),
                ('effective_date', models.DateField()),
                ('ingestion_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['provider_name', 'rate_type', 'effective_date'], name='rates_rate_provide_fadb28_idx'), models.Index(fields=['effective_date'], name='rates_rate_effecti_1bb52c_idx'), models.Index(fields=['rate_type'], name='rates_rate_rate_ty_237ee1_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider_name', 'rate_type', 'effective_date'), name='unique_rate_provider_type_date')],
            },
        ),
    ]
